// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isDigit(ch) {
  return /[0-9]/.test(ch);
}

function isAlpha(ch) {
  return /[a-zA-Z]/.test(ch);
}

exports.isDigit = isDigit;
exports.isAlpha = isAlpha;
/* No side effect */
